# .goreleaser.yml
project_name: eccovyx-agent

release:
  github:
    owner: eccovalue
    name: eccovyx-agent
  draft: false
  prerelease: false

builds:
  - id: linux
    main: ./linux/cmd/main.go
    binary: eccovyx-agent
    goos: [linux]
    goarch: [amd64]
    env: [CGO_ENABLED=0]
    ldflags: [-s -w]

  - id: windows
    main: ./windows/cmd/main.go
    binary: eccovyx-agent.exe
    goos: [windows]
    goarch: [amd64]
    env: [CGO_ENABLED=0]
    ldflags: [-s -w]

artifacts:
  - name_template: "{{ .ProjectName }}_Linux_{{ .Arch }}"
    type: archive
    format: zip
    ids: [linux]
    files:
      - linux/install/install.sh
      - linux/exporters/node_exporter

  - name_template: "{{ .ProjectName }}_Windows_{{ .Arch }}"
    type: archive
    format: zip
    ids: [windows]
    files:
      - windows/install/install.ps1
      - windows/exporters/windows_exporter.exe

checksum:
  name_template: "checksums.txt"
