name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: GoReleaser Build
    runs-on: ubuntu-latest

    permissions:
      contents: write # Necessário para criar releases

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
        
